FROM apache/airflow:2.9.1-python3.11

USER root
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock* ./
RUN uv pip install --system ".[airflow]"

COPY src/ ./src/


USER airflow
